Web/Web/Controllers/ProductReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class ProductReportController : BaseController
    {
        //
        // GET: /ProductReport/

        public ActionResult Index(long id)
        {
            Web.Models.ProductReportModel viewModel = new Models.ProductReportModel();
            XCLShouCang.BLL.TB_SearchKey searchKeyBLL = new XCLShouCang.BLL.TB_SearchKey();
            viewModel.SearchKeyModel = searchKeyBLL.GetModel(id);
            return View("~/Views/TMSearch/ProductReport.cshtml", viewModel);
        }

        public ActionResult GetTopProductCount()
        {
            XCLShouCang.BLL.TB_Product productBLL = new XCLShouCang.BLL.TB_Product();
            long searchKeyID = XCLNetTools.StringHander.FormHelper.GetLong("searchKeyID");
            List<XCLShouCang.Model.TB_ProductCountByShop> lst= productBLL.GetTopProductCountReport(searchKeyID);
            return Json(lst,JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetProductCountGroupProvince()
        {
            XCLShouCang.BLL.TB_Product productBLL = new XCLShouCang.BLL.TB_Product();
            long searchKeyID = XCLNetTools.StringHander.FormHelper.GetLong("searchKeyID");
            List<XCLShouCang.Model.TB_ProductCountGroupProvince> lst = productBLL.GetProductCountGroupProvince(searchKeyID);
            return Json(lst, JsonRequestBehavior.AllowGet);
        }


    }
}

Web/Web/Controllers/TMSearchController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class TMSearchController : BaseController
    {
        /// <summary>
        /// 商品信息列表
        /// </summary>
        public ActionResult ProductList(long id)
        {
            Web.Models.ProductListModel viewModel = new Models.ProductListModel();
            XCLShouCang.BLL.TB_SearchKey searchKeyBLL = new XCLShouCang.BLL.TB_SearchKey();
            XCLShouCang.BLL.TB_Product productBLL = new XCLShouCang.BLL.TB_Product();
            viewModel.SearchKeyModel=searchKeyBLL.GetModel(id);
            if (null != viewModel.SearchKeyModel)
            {
                viewModel.ProductList = productBLL.GetModelList(viewModel.SearchKeyModel.SearchKeyID);
            }
            ViewBag.Title = viewModel.SearchKeyModel.KeyName;
            return View("~/Views/TMSearch/ProductList.cshtml",viewModel);
        }

        /// <summary>
        /// 根据关键字，导出商品信息
        /// </summary>
        public void ProductOutPut()
        {
            long searchKeyID = XCLNetTools.StringHander.FormHelper.GetLong("searchKeyID");
            XCLShouCang.BLL.TB_SearchKey searchKeyBLL = new XCLShouCang.BLL.TB_SearchKey();
            XCLShouCang.BLL.TB_Product productBLL = new XCLShouCang.BLL.TB_Product();

            XCLShouCang.Model.TB_SearchKey keyModel=searchKeyBLL.GetModel(searchKeyID);
            if(null!=keyModel)
            {
                DataSet ds = productBLL.GetProductDataTable(keyModel.SearchKeyID);
                XCLNetTools.DataHandler.DataToExcel.OutPutExcel(new XCLNetTools.DataHandler.OutPutParamClass()
                {
                    ds = ds,
                    AutoDownLoad=true,
                    conTitle=new string[]{ string.Format("天猫关键字【{0}】的查询结果！",keyModel.KeyName)},
                    fileTitle=Web.Common.CommonHelper.WebInfo.WebName
                });
            }
        }

        [HttpPost]
        public ActionResult GoSearch()
        {
            XCLNetTools.Message.MessageModel msgModel = new XCLNetTools.Message.MessageModel();
            DateTime dtNow=DateTime.Now;

            #region 查询时间检测
            string lastSearchTimeSession = "lastSearchTimeSession";
            DateTime? lastSearchTime = Session[lastSearchTimeSession] as DateTime?;//最近一次查询时间
            if (null != lastSearchTime)
            {
                if (DateTime.Now.Subtract(Convert.ToDateTime(lastSearchTime)).TotalSeconds <= Web.Common.CommonHelper.WebInfo.TB_SearchIntervalSecond)
                {
                    msgModel.Message = string.Format("查询过于频繁，请{0}秒后再查询！", Web.Common.CommonHelper.WebInfo.TB_SearchIntervalSecond);
                    return Json(msgModel);
                }
            }
            #endregion

            #region 参数验证
            XCLShouCang.Model.TB_SearchKey keyModel = new XCLShouCang.Model.TB_SearchKey()
            {
                KeyType=XCLNetTools.StringHander.FormHelper.GetInt("hdSearchTypeValue"),
                KeyName = XCLNetTools.StringHander.FormHelper.GetString("kw"),
                CreateTime = dtNow
            };

            if (keyModel.KeyType == (int)Common.CommonHelper.SearchTypeEnum.天猫搜索列表链接)
            {
                if (keyModel.KeyName.IndexOf("http://", StringComparison.OrdinalIgnoreCase) < 0)
                {
                    keyModel.KeyName = string.Format("http://{0}", keyModel.KeyName);
                }

                if (!XCLNetTools.StringHander.PageValid.IsURL(keyModel.KeyName))
                {
                    msgModel.Message = "您指定的链接无效！";
                    return Json(msgModel);
                }
            }
            #endregion

            #region 执行进度监听
            string connectionID=XCLNetTools.StringHander.FormHelper.GetString("connectionID");
            Action<string> action_ShowProcess = new Action<string>((msg) =>
            {
                var currentClient = Microsoft.AspNet.SignalR.GlobalHost.ConnectionManager.GetHubContext<Web.Common.SignalR.MyChatHub>().Clients.Client(connectionID);
                currentClient.showProductListProcess(new Web.Models.Common.GetProductProcessModel()
                { 
                    Message=msg
                });
            });
            #endregion

            var currentType=(Web.Common.CommonHelper.SearchTypeEnum)keyModel.KeyType;
            switch (currentType)
            { 
                case Common.CommonHelper.SearchTypeEnum.天猫搜索关键字:
                case Common.CommonHelper.SearchTypeEnum.天猫搜索列表链接:
                    this.GrabeProductFromPage(keyModel, action_ShowProcess, msgModel);
                    break;
                case Common.CommonHelper.SearchTypeEnum.淘宝账号:
                    this.GrabeBuyerInfo(keyModel, action_ShowProcess, msgModel);
                    break;
            }
            
            Session[lastSearchTimeSession] = DateTime.Now;

            if (currentType == Common.CommonHelper.SearchTypeEnum.淘宝账号 && null != msgModel.CustomObject)
            {
                return PartialView("~/Views/UserControl/BuyerSearch/BuyerInfo.cshtml", msgModel.CustomObject);
            }
            else
            {
                return Web.Controllers.BaseController.XCLJsonResult(msgModel);
            }
        }

        /// <summary>
        /// 抓取取宝贝信息
        /// </summary>
        private void GrabeProductFromPage(XCLShouCang.Model.TB_SearchKey keyModel, Action<string> action_ShowProcess, XCLNetTools.Message.MessageModel msgModel)
        {
            DateTime dtNow = DateTime.Now;
            List<XCLShouCang.Model.TB_Product> productModelList = new List<XCLShouCang.Model.TB_Product>();
            XCLShouCang.Model.TB_Product productModel = null;

            //抓取url数据
            HtmlAgilityPack.HtmlDocument doc = new HtmlAgilityPack.HtmlDocument();

            action_ShowProcess("准备获取宝贝信息");

            #region 获取列表页数据
            string searchUrl = string.Empty;
            switch (keyModel.KeyType)
            {
                case (int)Common.CommonHelper.SearchTypeEnum.天猫搜索列表链接:
                    searchUrl = keyModel.KeyName;
                    break;
                default:
                    searchUrl = Web.Common.CommonHelper.WebInfo.TB_ProductSearchListURL.Replace("{kw}", System.Web.HttpUtility.UrlEncode(keyModel.KeyName, System.Text.Encoding.GetEncoding("GB2312")));
                    break;
            }
            string productListHTML = Web.Common.CommonHelper.DownLoadHTMLString(searchUrl);

            doc.LoadHtml(productListHTML);

            Regex numberRegex = new Regex(@"\d+");
            HtmlAgilityPack.HtmlNodeCollection productNodes = doc.DocumentNode.SelectNodes("//div[@id='J_ItemList']/div[@class='product'][@data-id]");
            if (null != productNodes && productNodes.Count > 0)
            {
                for (int i = 0; i < productNodes.Count; i++)
                {
                    if (i == 0 || (i + 1) % 5 == 0)
                    {
                        action_ShowProcess(string.Format("正在从搜索列表中提取第【{0}】个宝贝基本信息...", i + 1));
                    }

                    var productNode = productNodes[i];
                    var productNodeWrap = productNode.SelectSingleNode("div[@class='product-iWrap']");
                    productModel = new XCLShouCang.Model.TB_Product();
                    productModel.CreateTime = dtNow;
                    productModel.Sort = i + 1;
                    productModel.ID = XCLNetTools.StringHander.Common.GetLong(null != productNode.Attributes["data-id"] ? productNode.Attributes["data-id"].Value : "");

                    //图片
                    var imgNode = productNodeWrap.SelectSingleNode("child::div[@class='productImg-wrap']/a[@class='productImg']/img");
                    if (null != imgNode)
                    {
                        if (null != imgNode.Attributes["data-ks-lazyload"])
                        {
                            productModel.ImgURL = imgNode.Attributes["data-ks-lazyload"].Value;
                        }
                        else if (null != imgNode.Attributes["src"])
                        {
                            productModel.ImgURL = imgNode.Attributes["src"].Value;
                        }
                    }
                    //价格
                    var priceNode = productNodeWrap.SelectSingleNode("child::p[@class='productPrice']/em");
                    productModel.Price = XCLNetTools.StringHander.Common.GetDecimal(null != priceNode.Attributes["title"] ? priceNode.Attributes["title"].Value : "");
                    //标题
                    var titleNode = productNodeWrap.SelectSingleNode("child::p[@class='productTitle']/a");
                    if (null == titleNode)
                    {
                        titleNode = productNodeWrap.SelectSingleNode("child::div[@class='productTitle productTitle-spu']/a");//电器城
                    }
                    productModel.Title = null != titleNode ? titleNode.InnerText : string.Empty;
                    //店铺
                    var shopNode = productNodeWrap.SelectSingleNode("child::div[@class='productShop']/a");
                    productModel.ShopName = shopNode.InnerText;
                    productModel.ShopID = XCLNetTools.StringHander.Common.GetLong(new Regex(@"(user_number_id=)(\d+)").Match(null != shopNode.Attributes["href"] ? shopNode.Attributes["href"].Value : "").Groups[2].Value);
                    
                    productModel.ProductURL = Web.Common.CommonHelper.WebInfo.TB_ProductURL.Replace("{ID}", productModel.ID.ToString());
                    productModel.ShopURL = Web.Common.CommonHelper.WebInfo.TB_ShopURL.Replace("{ShopID}", productModel.ShopID.ToString());
                    productModelList.Add(productModel);
                }

            }

Web/Web/Views/TMSearch/ProductList.cshtml
@{
    Layout = "~/Views/Shared/MasterView/MainView.cshtml";
}
@model Web.Models.ProductListModel
<div class="panel panel-success">
    <div class="panel-heading">
        <center>
            <h1>以下为【
                                @if (Model.SearchKeyModel.KeyType == (int)Web.Common.CommonHelper.SearchTypeEnum.天猫搜索关键字)
                                {
                                    @Model.SearchKeyModel.KeyName
                                }
                                else
                                {
                                    @Html.Raw(string.Format("<a href='{0}' target='_blank'>查看链接</a>", Model.SearchKeyModel.KeyName))
                                }
                】的查询结果</h1>
        </center>
    </div>
    <div class="panel-body">
        <div class="row text-right" style="margin:10px;">
            <a href="@Url.Action("ProductOutPut", "TMSearch", new { searchKeyID=Model.SearchKeyModel.SearchKeyID })" target="_blank" class="btn btn-primary">导出为Excel</a>
        </div>

        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th class="text-center">序号</th>
                    <th class="text-center">图片</th>
                    <th class="text-center">标题</th>
                    <th class="text-center">店铺</th>
                    @*<th class="text-center">店铺所在地</th>*@
                    <th class="text-center">宝贝所在地</th>
                    <th class="text-center">价格</th>
                    <th class="text-center">月成交数</th>
                    <th class="text-center">累计评价数</th>
                    <th class="text-center">评分</th>
                </tr>
            </thead>
            <tbody>
                @{
                    if (null != Model.ProductList && Model.ProductList.Count > 0)
                    {
                        foreach (var m in Model.ProductList)
                        {
                    <tr>
                        <td class="text-center">
                            @Html.Raw(m.Sort <= 10 ? string.Format("<span class=\"label label-warning\">{0}</span>", m.Sort) : m.Sort.ToString())
                        </td>
                        <td class="text-center">
                            <a href="@Html.Raw(m.ProductURL)" target="_blank">
                                <img src='@Html.Raw(m.ImgURL)' style="width:40px;height:40px;"  class="XCLProductToolTip" data-content="<img src='@Html.Raw(m.ImgURL)' />" alt="@m.Title"/>
                            </a>
                        </td>
                        <td><a href="@Html.Raw(m.ProductURL)" target="_blank" title="@m.Title">@m.Title</a></td>
                        <td><a href="@m.ShopURL" target="_blank">@m.ShopName</a></td>
@*                        <td class="text-center">
                            @(string.Equals(m.ShopProvince, m.ShopCity) ? m.ShopCity : string.Format("{0}-{1}", m.ShopProvince, m.ShopCity))
                        </td>*@
                        <td class="text-center">
                            @(string.Equals(m.ProductProvince, m.ProductCity) ? m.ProductCity : string.Format("{0}-{1}", m.ProductProvince, m.ProductCity))
                        </td>
                        <td class="text-center">@m.Price</td>
                        
                        <td class="text-center">@m.MonthDealCount</td>
                        <td class="text-center">@m.AppraiseCount</td>
                        <td class="text-center">@m.Rate</td>
                    </tr>
                        }
                    }
                    else
                    {
                    <tr>
                        <td colspan="100" align="center">未查到任何数据！
                        </td>
                    </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        XCLShouCang.TMSearch.ProductList.Init();
    });
</script>

Web/Web/Views/TMSearch/ProductReport.cshtml
@{
    ViewBag.Title = "宝贝报表信息";
    Layout = "~/Views/Shared/MasterView/MainView.cshtml";
}
@model Web.Models.ProductReportModel

<input type="hidden" id="SearchKeyID" value="@Model.SearchKeyModel.SearchKeyID" />

<div class="panel panel-success">
    <div class="panel-heading">
        <center>
            <h1>
                以下为【
                @if (Model.SearchKeyModel.KeyType == (int)Web.Common.CommonHelper.SearchTypeEnum.天猫搜索关键字)
                {
                        @Model.SearchKeyModel.KeyName
                    }else{
                        @Html.Raw(string.Format("<a href='{0}' target='_blank'>查看链接</a>",Model.SearchKeyModel.KeyName))
                    }
                
                】的统计报表
            </h1>
        </center>
    </div>
    <div class="panel-body">
        <div id="divProductCountRep" style="height:300px;"></div>
        <br />
        <div id="divProductProvinceCountRep" style="height:300px;"></div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        XCLShouCang.TMSearch.ProductReport.Init();
    });
</script>